### ISSUE TITLE
Cards sometimes freeze above the player or enemies instead of playing them.

### ISSUE THREAD

**Issue by Vesper-arch** [oskarrough/slaytheweb#222] opened 2024-01-10 16:39 UTC
This seems to happen randomly with no real pattern.
Screenshot:
![Screenshot 2024-01-10 08 35 19](https://github.com/oskarrough/slaytheweb/assets/137581120/cf53d590-4fee-49d5-9755-5ff938052659)

**Comment by oskarrough** [comment] 2024-01-11 20:00
Thank you for opening the issue. Yea, I've noticed as well.. I also don't yet understand why it happens. 

When you play a card I copy the DOM element of the card, and animate this copy. The problem is likely related to that combined with the drag 'n drop events.

**Comment by Vesper-arch** [comment] 2024-01-12 17:56
What's the DOM element, I don't really know java-script that well.

**Comment by oskarrough** [comment] 2024-01-16 12:17
Okay it seems to happen, at least, when you play the "Summer of Sam" card. Looking into why.. something with a wrong card target.

![screenshot 2024-01-16 at 12 05 52](https://github.com/oskarrough/slaytheweb/assets/184567/b72e30f8-92f4-44de-a9fa-1c801369107c)

I hope I've fixed in #223. Please give it ago on slaytheweb.cards, if you can :) Many thanks for reporting the issue again.

**Closed** 2024-01-16 12:16 UTC
Labels: bug

**Comment by Vesper-arch** [comment] 2024-01-20 01:49
Fyi, it happens with other cards too, I didn't have that card and it started freezing any cards that I played on anything.

**Comment by Vesper-arch** [comment] 2024-01-20 01:58
Also, could you recommend a good java-script course? I would love to help out on the coding side of things but I only know Python fluently

**Comment by oskarrough** [comment] 2024-01-20 09:00
Depending on your experience there is a ton of information on the MDN site https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps.

But if you already know Python, maybe you can just jump in! Is there something specific you'd like to try with the game? Then I could say how I'd approach it, maybe that helps.

**Comment by Vesper-arch** [comment] 2024-01-20 18:24
Oof, I don't even know where to start with trying stuff out on the game. I think I'll go through the JS course and see what I can do then.
